# Uncomment this line to define a global platform for your project
platform :ios, "6.0"
pod 'Facebook-iOS-SDK',       '~> 3.15.0'
pod 'Parse' #Login via Facebook
pod 'AWSiOSSDK', '~> 1.7'
#pod 'US2FormValidator', '~> 1.1.2' #form validation
